version: 2
jobs:
  build:
    working_directory: ~/tmp
    docker:
      - image: circleci/node:4.8.4
#      - image: mongo:3.4.4
    steps:
      - checkout
      - run: curl https://install.meteor.com | sh
      - run: sudo sed -i -e 's/# en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/' /etc/locale.gen && sudo dpkg-reconfigure --frontend=noninteractive locales
      - run: meteor npm install
      - run: meteor test --once --driver-package dispatch:mocha
