version: 2
jobs:
  build:
    working_directory: ~/tmp
    docker:
      - image: circleci/ubuntu:16.04
    steps:
      - checkout
      - run: https://install.meteor.com | sh
      - run: npm install
      - run: meteor test --once --driver-package dispatch:mocha
